### ISSUE TITLE
Some of the hyperlinks are invalid

### ISSUE THREAD

**Issue by k----n** [dpvcg/dpv#2]
I'm not sure if this is intended, but a lot of the hyperlinks inside the document lead to invalid links.

e.g. https://dpvcg.github.io/extract-sheets/index.html#purpose-classes
All the links under those sections are invalid.

**Comment by coolharsh55** [comment]
Thank you for pointing this out. I've fixed this issue in the [latest commit](https://github.com/dpvcg/dpv/commit/f8786271041abb5e2bcddf3eff89935ab4a82c3b).

**Comment by k----n** [comment]
Hi,

I just noticed another hyperlink issue.

`<a href="DPVCG">DPVCG</a>`

and

`<a href="SPECIAL">SPECIAL</a>`

are also dead links.

I'm not sure where they are intended to go.

**Comment by coolharsh55** [comment]
Thanks. These links, along with the ones for external references, such as `rdfs:comment` and `time:Instant` will be resolved in the next commit.
