### ISSUE TITLE
How to cite this work?

### ISSUE THREAD

**Issue by ralienpp** [dpvcg/dpv#5]
Hi, I am working on a paper that is related to privacy, and where one of the recommendations is to use a unified terminology, to reduce confusion among users. Do you have a preferred way in which you want this research to be cited? It would be great if you included this info in the readme.

**Comment by coolharsh55** [comment]
If you want to cite the vocabulary, you can cite the vocabulary specification web page [1], or you can cite the following paper (update: published) [2]. A previous paper explaining the starting aims of the CG and initial work is also available [3].

 1. Data Privacy Vocabulary v0.1 ( Draft Community Group Report 26 July 2019), http://w3.org/ns/dpv (editors...)
 2. Creating A Vocabulary for Data Privacy, authors: Pandit, Harshvardhan J. and Polleres, Axel and Bos, Bert and Brennan, Rob and Bruegger, Bud and Ekaputra, Fajar J and Fernandez, Javier D and Hamed, Roghaiyeh Gachpaz and Lizar, Mark and Schlehahn, Eva and Steyskal, Simon and Wenning, Rigo. 18th International Conference on Ontologies, DataBases, and Applications of Semantics (ODBASE2019), Rhodes, Greece 2019. (accepted, to-be presented)
 3. Data privacy vocabularies and controls: Semantic web for transparency and privacy. authors: Bonatti, PA and Bos, B and Decker, S and Fernandez, JD and Kirrane, S and Peristeras, V and Polleres, A and Wenning, R. Workshop on Semantic Web for Social Good (SW4SG2018), co-located with 17th International Semantic Web Conference (ISWC 2018)
Monterey, California, USA. CEUR Workshop Proceedings  volume 2182, 2018

**Comment by coolharsh55** [comment]
I have the citation to the README.md for this repo, and have made a note to also mention it in the HTML documentation.

**Comment by coolharsh55** [comment]
The citation reference is now present the README
