### ISSUE TITLE
DataSubject is not defined as sub-class of LegalEntity

### ISSUE THREAD

**Issue by k----n** [dpvcg/dpv#7]
Happy Holidays!

Just noticed that in w3, some relationships are defined that are not in the ttl of this repo:

E.g.
In w3:
`https://www.w3.org/ns/dpv#dpv:LegalEntity is Parent Class of dpv:DataSubject`

In ttl (https://github.com/dpvcg/dpv/blob/07526f2c287b9503d4dc9a407e5f10fc688fc85b/dpv.ttl#L616):
`dpv:DataSubject a rdfs:Class ; doesn't have rdfs:subClassOf dpv:LegalEntity`

**Comment by coolharsh55** [comment]
Thanks for raising this point. We'd like to ideally have an Entity class to represent the set of all entities - Controllers, Processors, Recipients, etc.

**Comment by coolharsh55** [comment]
fixed in https://github.com/dpvcg/dpv/commit/cee6df02103acc68c5714cec5b3c8548c64a2faa
